<?php

require_once(getcwd() . "/sites/all/libraries/Spout/Autoloader/autoload.php");

use Box\Spout\Reader\ReaderFactory;
use Box\Spout\Common\Type;

function importer_menu()
{
  $items = array();
  $items['importer/psehk_importer'] = array(
    'title' => 'PSEHK product importer',
    'description' => 'PSEHK product importer',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('importer_form'),
    'access callback' => TRUE
  );
  return $items;
}

function importer_form($form, &$form_state)
{
  $form['file'] = array(
    '#type' => 'file',
    '#name' => 'file',
    '#title' => t('File'),
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Import'),
  );

  return $form;
}

function importer_form_validate($form, &$form_state)
{
  if ($_FILES["file"]["error"] !== UPLOAD_ERR_OK) {
    form_set_error('file', t('Excel file is required'));
  }
}

function importer_form_submit($form, &$form_state)
{
  $filePath = $_FILES["file"]["tmp_name"];
  $reader = ReaderFactory::create(Type::XLSX);
  $reader->open($filePath);
  foreach ($reader->getSheetIterator() as $sheet) {
    switch ($sheet->getName()) {
      case "product":
        importer_handle_product_tab($sheet);
        break;
      case "product_variation":
      case "product_specification":
        importer_handle_product_specification_tab($sheet);
        break;
      case "pq_curve":
      case "support_document":
      case "accessory":
      case "related_product":
      default:
        importer_handle_product_tab($sheet);
        break;
    }
  }
  drupal_set_message(t('Excel file imported'));
  $reader->close();
}

function importer_handle_product_tab($sheet)
{
  foreach ($sheet->getRowIterator() as $key => $row) {
    if ($key == 1) {
      continue;
    }
    importer_create_product_node($row);
  }
}

function importer_handle_product_specification_tab($sheet)
{
  foreach ($sheet->getRowIterator() as $key => $row) {
//    if ($key == 1) {
//      continue;
//    }
    importer_create_product_specification($row);
  }
}

function importer_create_product_node($row)
{
  global $user;

  $title = $row[0];
  $product_name = $row[1];
  $product_thumbnail = $row[2];
  $product_description = $row[3];
  $product_sku = $row[4];
  $features = $row[5];
  $product_catagory = $row[6];
  $photos = $row[7];

  // field values preprocessing
  $product_description = "<ul><li>" . implode("</li><li>", explode("\n", $product_description)) . "</li></ul>";
  $features = "<ul><li>" . implode("</li><li>", explode("\n", $features)) . "</li></ul>";
  $terms = taxonomy_get_term_by_name($product_catagory);
  if (is_array($terms)) {
    foreach ($terms as $term) {
      if ($term->vocabulary_machine_name == 'product_category') {
        $folderid = $term->tid;
        break;
      }
    }
  }

  // create node
  $values = array(
    'type' => 'product',
    'uid' => $user->uid,
    'status' => 1,
    'comment' => 1,
    'promote' => 0,
  );
  $entity = entity_create('node', $values);
  $ewrapper = entity_metadata_wrapper('node', $entity);


  // set node values
  $ewrapper->title->set($title);
  $ewrapper->field_product_name->set($product_name);
  $ewrapper->field_product_thumbnail->set((array)importer_get_file_by_filename($product_thumbnail));
  $ewrapper->field_product_description->set(['value' => $product_description, 'format' => 'full_html']);
  $ewrapper->field_product_sku->set($product_sku);
  $ewrapper->field_product_featues->set(['value' => $features, 'format' => 'full_html']);
  $ewrapper->field_product_catagory->set($folderid);
  $ewrapper->save();
}

function importer_create_product_specification($row)
{
  global $user;
  $product_title = $row[0]; // "FV-17CU7"


  $title = "abc";
  $field_voltage = "110";


  // create node
  $values = array(
    'type' => 'product_specification',
    'uid' => $user->uid,
    'status' => 1,
    'comment' => 1,
    'promote' => 0,
  );
  $entity = entity_create('node', $values);
  $ewrapper = entity_metadata_wrapper('node', $entity);


  // set node values
//  $ewrapper->title->set($title);
//  $ewrapper->field_voltage->set($field_voltage);
//  $ewrapper->save();

  // update product
//  $product = importer_get_prodcut_by_title($product_title);
//  $node_wrapper = entity_metadata_wrapper('node', $product);
//  $node_wrapper->field_product_specification->set([$ewrapper->value()->nid]);
//  $node_wrapper->save();
}

// helper function: get_product_by_title
function importer_get_prodcut_by_title($title)
{
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->propertyCondition('title', '%' . $title . '%', 'LIKE');
  $result = $query->execute();
  if (!empty($result['node'])) {
    foreach ($result['node'] as $node) {
      if ($node->type == 'product') {
        $node = entity_load('node', [$node->nid]);
        return current($node);
      }
    }
  }
  return null;
}

// helper function: get_file_by_filename
function importer_get_file_by_filename($filename)
{
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'file')
    ->propertyCondition('filename', '%' . $filename . '%', 'LIKE');
  $result = $query->execute();
  if (!empty($result['file'])) {
    $files = entity_load('file', array_keys($result['file']));
    $drupal_file = current($files); // get first item
  }

  return $drupal_file;
}
